-- MySQL Script generated by MySQL Workbench
-- mar 17 may 2022 18:27:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP database if exists `CROSSTube-VMI`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CROSSTube-VMI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CROSSTube-VMI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CROSSTube-VMI` ;
USE `CROSSTube-VMI` ;

-- -----------------------------------------------------
-- Table `CROSSTube-VMI`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CROSSTube-VMI`.`Usuario` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CROSSTube-VMI`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CROSSTube-VMI`.`Nivel` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `CROSSTube-VMI`.`Ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CROSSTube-VMI`.`Ejercicio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `tipo` ENUM("MUSCULACION","CARDIO") NOT NULL,
  `autoCarga` boolean NOT NULL,
  `nivel_id` INT NOT NULL,
  `grupoMuscular` enum("HOMBROS","ESPALDA","BICEPS","TRICEPS","PECHO","ABDOMINAL","GLUTEOS","CUADRICEPS","PIENAS","LUMBAR","GRIP","CARDIO") NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ejercicio_Nivel1_idx` (`nivel_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ejercicio_Nivel1`
    FOREIGN KEY (`nivel_id`)
    REFERENCES `CROSSTube-VMI`.`Nivel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CROSSTube-VMI`.`Visualiza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CROSSTube-VMI`.`Visualiza` (
  `Usuario_id` INT NOT NULL,
  `Ejercicio_id` INT NOT NULL,
  PRIMARY KEY (`Usuario_id`, `Ejercicio_id`),
  INDEX `fk_Usuario_has_Ejercicio_Ejercicio1_idx` (`Ejercicio_id` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Ejercicio_Usuario1_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Ejercicio_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `CROSSTube-VMI`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Ejercicio_Ejercicio1`
    FOREIGN KEY (`Ejercicio_id`)
    REFERENCES `CROSSTube-VMI`.`Ejercicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;